### PR TITLE
feat: upgrade VCN module to 3.4.0

### LINKED ISSUE #479: Upgrade VCN to 3.3.0
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We have had a few releases with the VCN module but the OKE module has not kept up. We need to upgrade to VCN 3.3.0 to enjoy the new features such as using the new DRG submodule, RPC and support for defined tags.

### Potential Terraform Configuration

```hcl
# Copy-paste any Terraform configurations for how the requested feature may be used. 
```

### PR DESCRIPTION
**Pull request by snafuz**
close #479

### CODE REVIEW

**Comment by hyder** [comment]
If I set `create_drg       = true` and then put the routing rules:

`nat_gateway_route_rules = [
   {
      destination       = "10.1.0.0/16"
      destination_type  = "CIDR_BLOCK"
      network_entity_id = "drg"
      description       = "To Sydney"
    }
]`

this fails:

│ Error: Invalid index
│
│   on .terraform/modules/vcn/vcn_gateways.tf line 157, in resource "oci_core_route_table" "nat":
│  157:       network_entity_id = module.drg_from_vcn_module[0].drg_id
│     ├────────────────
│     │ module.drg_from_vcn_module is empty tuple
│
│ The given key does not identify an element in this collection value: the collection has no elements.
╵
╷
│ Error: Invalid index
│
│   on .terraform/modules/vcn/vcn_gateways.tf line 157, in resource "oci_core_route_table" "nat":
│  157:       network_entity_id = module.drg_from_vcn_module[0].drg_id
│     ├────────────────
│     │ module.drg_from_vcn_module is empty tuple
│
│ The given key does not identify an element in this collection value: the collection has no elements.
╵
╷
│ Error: Invalid index
│
│   on .terraform/modules/vcn/vcn_gateways.tf line 157, in resource "oci_core_route_table" "nat":
│  157:       network_entity_id = module.drg_from_vcn_module[0].drg_id
│     ├────────────────
│     │ module.drg_from_vcn_module is empty tuple
│
│ The given key does not identify an element in this collection value: the collection has no elements.

The reasoning behind the value of `network_entity_id = "drg"` is that the route table will add a rule that will set the destination to the drg created by the vcn module. The only way I can get this to work is by first running terraform to create the drg, and then running terraform again to set the drg ocid directly.

**Comment by hyder** [comment]
@snafuz Please use v3.4.0 instead so we can include the provider change

**Comment by snafuz** [comment]
@hyder  WIP - I've found a side-effect caused by the latest changes on vcn module that occurs when drg submodule is created in the network submodule. I'm working on a solution to fix it.

**Comment by snafuz** [comment]
@hyder - I've upgraded VCN module to 3.4.0

> **Caveat**: the DRG is still handled as an internal submodule

**Review by hyder — APPROVED** [review]
approved

**Pull request merged**
