### PR TITLE
added a generated suffix so dynamic group name for operator to update…

### PR DESCRIPTION
**Pull request by hyder**
… kms will be unique

### CODE REVIEW

**Comment by hyder** [comment]
Closes #231

**Review by karthicgit — APPROVED** [review]

**Review by karthicgit — APPROVED** [review]
Reviewed

**Review by karthicgit — APPROVED** [review]
Reviewed looks good.

**Review by hyder — COMMENTED** [review]
Required to prevent instance_principal group creation from failing

**Review by Djelibeybi — APPROVED** [review]

**Pull request merged**
