### PR TITLE
feat: Optionally ignore the label prefix in node pool names

### PR DESCRIPTION
**Pull request by christophercorn**
https://github.com/oracle-terraform-modules/terraform-oci-oke/issues/628

An OKE nodepool is limited to 32 chars.

var.label_prefix can sometimes consume most of those chars, leaving little room for the remainder of the node pool name as defined in each key name of var.node_pools.

for a more descriptive nodepool name we should have the ability to drop the var.label_prefix name specifically for the oci_containerengine_node_pool resource. this way, we can maintain the functionality of var.label_prefix that is used across this terraform module.

to validate this change:
```
module "oke" {
  source = "oracle-terraform-modules/oke/oci"
  ignore_label_prefix_in_node_pool_names = true  
  ....
}
```

### CODE REVIEW

**Comment by hyder** [comment]
Why not use the value ```none``` in your case for the label prefix? It will achieve the same effect.

**Comment by christophercorn** [comment]
> Why not use the value `none` in your case for the label prefix? It will achieve the same effect.

 Label_prefix is used widely by many other resources in the terraform-oci-oke module. Changing label_prefix will affect many other resources that don’t have a small 32 char limitation. The suggested implementation only affects node pool resource name.

**Comment by hyder** [comment]
> > Why not use the value `none` in your case for the label prefix? It will achieve the same effect.
> 
> Label_prefix is used widely by many other resources in the terraform-oci-oke module. Changing label_prefix will affect many other resources that don’t have a small 32 char limitation. The suggested implementation only affects node pool resource name.

So you want to keep the label_prefix for the other resources but keep it optional for node pools in case the name is too long?

**Comment by christophercorn** [comment]
> > > Why not use the value `none` in your case for the label prefix? It will achieve the same effect.
> > 
> > 
> > Label_prefix is used widely by many other resources in the terraform-oci-oke module. Changing label_prefix will affect many other resources that don’t have a small 32 char limitation. The suggested implementation only affects node pool resource name.
> 
> So you want to keep the label_prefix for the other resources but keep it optional for node pools in case the name is too long?

Yes, that would be very helpful.

**Comment by christophercorn** [comment]
Can someone review this and possible approve?

**Comment by hyder** [comment]
Hi, sorry for the delay. 

@devoncrouse and I have been discussing this and we will drop the `label_prefix` in the next major release.

**Comment by christophercorn** [comment]
@hyder  do you know when 5.0 will be released?

**Comment by hyder** [comment]
> @hyder do you know when 5.0 will be released?

We just cut the 1st beta release for 5.x. @devoncrouse does it include dropping the `label_prefix` ?

**Review by devoncrouse — APPROVED** [review]
We'll be deprecating `label_prefix` in 5.x, but we can add this to 4.x in the meantime.

**Comment by christophercorn** [comment]
> We'll be deprecating `label_prefix` in 5.x, but we can add this to 4.x in the meantime.

thanks @devoncrouse

**Comment by hyder** [comment]
No, not yet unfortunately. We just released the 2nd beta yesterday.

**Comment by lodotek** [comment]
> We'll be deprecating `label_prefix` in 5.x, but we can add this to 4.x in the meantime.

Can i find some notes regarding this deprecation? This is causing me frustration when trying to use the latest RC.

**Pull request merged**
