### PR TITLE
added support for out-of-place upgrade

### LINKED ISSUE #150: Add option to enable admission controller/pod security policy
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Pod security policy is now supported on OKE: https://docs.cloud.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengusingpspswithoke.htm. 

To do:
1) Add an option to enable the admission controller and pod security policy 
2) Research whether this is mutually exclusive wrt using calico

### Potential Terraform Configuration

```hcl
# Copy-paste any Terraform configurations for how the requested feature may be used. 
```

### LINKED ISSUE #178: Support Cluster Upgrade through automation
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

    Upgrade Master Nodes on an existing terraform deployed oke cluster
    Upgrade Worker Nodes on an existing terraform deployed oke cluster

### Potential Terraform Configuration

```hcl
# Copy-paste any Terraform configurations for how the requested feature may be used. 
```

### References

https://docs.cloud.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengupgradingk8smasternode.htm
https://docs.cloud.oracle.com/en-us/iaas/Content/ContEng/Tasks/contengupgradingk8sworkernode.htm

### PR DESCRIPTION
**Pull request by hyder**
Resolves #150 #178 #179 #181 #182 #185

### CODE REVIEW

**Comment by hyder** [comment]
@karthicgit @livespotty: can you please test? Instructions for upgrade are in the upgrade file under docs.

**Comment by livespotty** [comment]
Followed upgrade.adoc and tested the cluster upgrade and works fine.

1)	Created new cluster np1=version 1.15.7 
2)	Upgraded the master with version 1.16.8
3)	Added new nodepool np2=version 1.16.8
4)	Drain nodepool np1 and tested if it moves the state to “Ready,SchedulingDisabled" 
5)	Delete the nodepool np1

**Comment by hyder** [comment]
Closes #178

**Comment by orisvscs** [comment]
Tested and the procedure worked. Awesome job...

**Pull request merged**
