### PR TITLE
fix: Update link to Oracle Contributor Agreement

### PR DESCRIPTION
**Pull request by rodrigc**
Signed-off-by: Craig Rodrigues <craig@quiknode.io>

### CODE REVIEW

**Review by hyder — APPROVED** [review]

**Review by hyder — APPROVED** [review]
Approved

**Comment by rodrigc** [comment]
@hyder any idea why this PR still says:

```
Merging is blocked
The base branch requires all commits to be signed
```

All my commits are signed in this PR.

I have the same problem here: https://github.com/oracle-terraform-modules/terraform-oci-oke/pull/744#issuecomment-1601942249

**Comment by devoncrouse** [comment]
Hey @rodrigc - this is checking for GPG signing rather than the signoff, if that could be the issue. Are you committing with `-S` or have this configured by default? You can take a look [here](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification) for more information on creating/telling Git about your signing key if needed. A `git commit -S --amend` and re-push should address following that.

```shell
man git-commit | grep -EA1 "(--signoff|--gpg-sign)"
       -s, --signoff
           Add Signed-off-by line by the committer at the end of the commit log message. The meaning of a signoff depends on the project, but it typically certifies that committer has the rights to submit this work under the same license and agrees to a Developer Certificate of Origin (see
--
       -S[<keyid>], --gpg-sign[=<keyid>]
           GPG-sign commits. The keyid argument is optional and defaults to the committer identity; if specified, it must be stuck to the option without a space.
```

**Comment by rodrigc** [comment]
I used the `-s | --signoff` flag as specified in: https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/5.x/CONTRIBUTING.md#contributing-to-the-terraform-oci-oke-repository

There is no mention of a requirement for GPG signing in that doc.

**Comment by rodrigc** [comment]
I tried this:

```
git commit -S --amend
```

and got:

```
error: cannot run gpg: No such file or directory
error: gpg failed to sign the data
fatal: failed to write commit object
```

I you sure that I need to install gpg to sign my commits that way?
I haven't used gpg for anything in about 15 years.

**Comment by hyder** [comment]
Hi @rodrigc,

Sorry for the trouble. My understanding is that it's Oracle's policy to request that commits be signed. @Djelibeybi can you please confirm?

GitHub's gpg guide: https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key

**Comment by rodrigc** [comment]
@hyder I signed my commits with `git commit -s` which is what is documented here:
https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/5.x/CONTRIBUTING.md#contributing-to-the-terraform-oci-oke-repository


This also passed the checks of the bot which checks commits for compliance with the OCA:

https://github.com/oracle-terraform-modules/terraform-oci-oke/pull/743/checks?check_run_id=14456943328

There is no mention of gpg signed commits as a requirement.

**Comment by rodrigc** [comment]
@devoncrouse @Djelibeybi @hyder Can you confirm if Oracle needs GPG or SSH signed commits to merge? 
That's not clear from here: https://github.com/oracle-terraform-modules/terraform-oci-oke/blob/5.x/CONTRIBUTING.md#contributing-to-the-terraform-oci-oke-repository

**Comment by devoncrouse** [comment]
Hi @rodrigc, this is a standard Github check enabled for this repository - you can find configuration instructions [here](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification). It looks like either should be supported.

**Comment by Djelibeybi** [comment]
This repo requires a linear git history (so rebase, don't FF merge) but it does not require signed commits, at least not for PRs to `main`.

**Comment by rodrigc** [comment]
> This repo requires a linear git history (so rebase, don't FF merge) but it does not require signed commits, at least not for PRs to `main`.

@Djelibeybi Are you sure?  The checks for this PR show:

```
Merging is blocked
The base branch requires all commits to be signed. [Learn more about signing commits.](https://docs.github.com/articles/about-gpg/)
```

So that would seem to indicate that this repo has been configured to require signed commits?

**Comment by Djelibeybi** [comment]
Whoops, I missed that nugget of information. I've removed the requirement for signed commits to the `5.x` branch, though I strongly encourage you to sign your commits anyway. :)

**Comment by rodrigc** [comment]
@Djelibeybi In future if signed commits are required, I would suggest adding the requirement to the `CONTRIBUTING`.

Thanks for the prompt fix!  I can verify that my PR is now unblocked.

**Pull request merged**
