### PR TITLE
201 ad specific node deployment nodepool

### LINKED ISSUE #201: Granular control on deploying instances in node pools in specific ADs
Would be good to implement support to deploy multiple instances to a single AD/ subset of ADs which is possible via the Cloud Console. 

At present a definition like below would round-robin across the ADs instead of deploying both VMs in the same AD.

node_pools = {
  np1 = ["VM.Standard2.8", 2]
  np2 = ["VM.Standard2.4", 2]
}

Perhaps a definition like this would help define np1 to span across AD1 and AD2 while np2 will deploy 2 instances in AD1

node_pools = {
  np1 = ["VM.Standard2.8", "AD1, AD2", 2]
  np2 = ["VM.Standard2.4", "AD1", 2]
}

### PR DESCRIPTION
**Pull request by pradeep-gangappa**
Fix #201 
Added changes to select AD preference in nodepool 

@karthicgit  I have made changes, can you please review and comment if anything needed.

### CODE REVIEW

**Comment by hyder** [comment]
cool. I'll wait for @karthicgit to finish his review before merging.

**Comment by karthicgit** [comment]
@pradeep-gangappa   May i know you have tested this on single AD region as well.

**Comment by pradeep-gangappa** [comment]
Yes code has been written to work with single AD region as well and its tested. 

Note: when user given non existing AD , say suppose in single AD region if they give AD2 it will take its as AD1 

 input values to Canada Southeast (Toronto) region 
image

image

**Comment by pradeep-gangappa** [comment]
@karthicgit  if you have no concerns let @hyder know , he will merge and close this pull request.

**Pull request closed without merging**
