### PR TITLE
issue #203 node pool label fix

### LINKED ISSUE #203: Add default K8s labels to node pools
Add default K8s labels to node pools like the below which can be used in nodeSelector to deploy pods to a particular node pool.

Labels:
name="name-of-node-pool"

for ex: 
name="dev-np1"

### PR DESCRIPTION
**Pull request by kumararv2009**
Fix  #203 Signed-off-by: kumararv2009 <arvind.b.kumar@oracle.com>

### CODE REVIEW

**Comment by kumararv2009** [comment]
@hyder can you please review the changes .

**Comment by hyder** [comment]
Thanks for your contribution. Can you please also illustrate in the how the label values would be passed? What data structure are you using? I couldn't see that in your code.

**Comment by kumararv2009** [comment]
@hyder the label for node pool is going to be same as the node pool name .It is going to add label as requested in the issue . 
Labels:
name="name-of-node-pool"
Please let me know if its fine or any change required .

**Comment by hyder** [comment]
Labels can be more than 1. It doesn't seem that the proposed node labels can handle that.

**Comment by hyder** [comment]
@kumararv2009 will you be adding further enhancements so more than 1 label can be added??

**Comment by hyder** [comment]
Lack of response. If you would like to contribute to this feature, please address the limitations on the labels as described above and reopen your PR. I'll be closing this for now.

**Pull request closed without merging**
