### PR TITLE
Reuse vcn for Issues #171 and #163

### PR DESCRIPTION
**Pull request by karthicgit**
OKE cluster can be created using existing VCN.

### CODE REVIEW

**Comment by Pixy123** [comment]
Hi, this feature will merged in master? I have checked but for now it's only a branch. Thanks

**Comment by litewhatever** [comment]
@hyder can you comment on vcn_reuse branch merge to master?
In my case I also need to run managed databases, but I do not like the idea of hard dependency between OKE VCNs and my database instances.

**Comment by hyder** [comment]
> @hyder can you comment on `reuse-vcn` branch merge/feature release to master?
> In my case I need to run managed databases, but I do not like the idea of hard dependency between OKE VCNs and my database instances.

Hi,

This was what we concluded before: https://github.com/oracle-terraform-modules/terraform-oci-oke/issues/163#issuecomment-638529445

Can you please elaborate on your issue/needs? Maybe we can revisit.

**Comment by litewhatever** [comment]
> > @hyder can you comment on `reuse-vcn` branch merge/feature release to master?
> > In my case I need to run managed databases, but I do not like the idea of hard dependency between OKE VCNs and my database instances.
> 
> Hi @litewhatever,
> 
> This was what we concluded before: [#163 (comment)](https://github.com/oracle-terraform-modules/terraform-oci-oke/issues/163#issuecomment-638529445)
> 
> Can you please elaborate on your issue/needs? Maybe we can revisit.

Our intention was to deploy VCN/network with terraform and then reuse it for OKE, managed databases and other managed services provided by OCI.

**Pull request merged**
